-- STEP 9: ROW LEVEL SECURITY POLICIES
-- Run after step 8

ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE taste_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE roast_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_taste_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_roast_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_graph_1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_graph_2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_graph_3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE discount_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE favourites ENABLE ROW LEVEL SECURITY;
ALTER TABLE sample_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "View companies" ON companies; CREATE POLICY "View companies" ON companies FOR SELECT USING (is_approved_wholesale() OR is_admin());
DROP POLICY IF EXISTS "Admins manage companies" ON companies; CREATE POLICY "Admins manage companies" ON companies FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "Users view profile" ON profiles; CREATE POLICY "Users view profile" ON profiles FOR SELECT USING (auth.uid()=id OR is_admin());
DROP POLICY IF EXISTS "Users update profile" ON profiles; CREATE POLICY "Users update profile" ON profiles FOR UPDATE USING (auth.uid()=id);
DROP POLICY IF EXISTS "Users insert profile" ON profiles; CREATE POLICY "Users insert profile" ON profiles FOR INSERT WITH CHECK (auth.uid()=id);
DROP POLICY IF EXISTS "View categories" ON categories; CREATE POLICY "View categories" ON categories FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage categories" ON categories; CREATE POLICY "Admins manage categories" ON categories FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View collections" ON collections; CREATE POLICY "View collections" ON collections FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage collections" ON collections; CREATE POLICY "Admins manage collections" ON collections FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View taste" ON taste_profiles; CREATE POLICY "View taste" ON taste_profiles FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage taste" ON taste_profiles; CREATE POLICY "Admins manage taste" ON taste_profiles FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View roast" ON roast_profiles; CREATE POLICY "View roast" ON roast_profiles FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage roast" ON roast_profiles; CREATE POLICY "Admins manage roast" ON roast_profiles FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View products" ON products; CREATE POLICY "View products" ON products FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage products" ON products; CREATE POLICY "Admins manage products" ON products FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View product collections" ON product_collections; CREATE POLICY "View product collections" ON product_collections FOR SELECT USING (true);
DROP POLICY IF EXISTS "View product taste" ON product_taste_profiles; CREATE POLICY "View product taste" ON product_taste_profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "View product roast" ON product_roast_profiles; CREATE POLICY "View product roast" ON product_roast_profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "View graph1" ON product_graph_1; CREATE POLICY "View graph1" ON product_graph_1 FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage graph1" ON product_graph_1; CREATE POLICY "Admins manage graph1" ON product_graph_1 FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View graph2" ON product_graph_2; CREATE POLICY "View graph2" ON product_graph_2 FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage graph2" ON product_graph_2; CREATE POLICY "Admins manage graph2" ON product_graph_2 FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View graph3" ON product_graph_3; CREATE POLICY "View graph3" ON product_graph_3 FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage graph3" ON product_graph_3; CREATE POLICY "Admins manage graph3" ON product_graph_3 FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "Users view cart" ON carts; CREATE POLICY "Users view cart" ON carts FOR SELECT USING (auth.uid()=user_id OR session_id IS NOT NULL);
DROP POLICY IF EXISTS "Users manage cart" ON carts; CREATE POLICY "Users manage cart" ON carts FOR ALL USING (auth.uid()=user_id OR session_id IS NOT NULL);
DROP POLICY IF EXISTS "Users view cart items" ON cart_items; CREATE POLICY "Users view cart items" ON cart_items FOR SELECT USING (EXISTS(SELECT 1 FROM carts WHERE carts.id=cart_items.cart_id AND (carts.user_id=auth.uid() OR carts.session_id IS NOT NULL)));
DROP POLICY IF EXISTS "Users manage cart items" ON cart_items; CREATE POLICY "Users manage cart items" ON cart_items FOR ALL USING (EXISTS(SELECT 1 FROM carts WHERE carts.id=cart_items.cart_id AND (carts.user_id=auth.uid() OR carts.session_id IS NOT NULL)));
DROP POLICY IF EXISTS "View discounts" ON discounts; CREATE POLICY "View discounts" ON discounts FOR SELECT USING (is_active=true);
DROP POLICY IF EXISTS "Admins manage discounts" ON discounts; CREATE POLICY "Admins manage discounts" ON discounts FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View discount products" ON discount_products; CREATE POLICY "View discount products" ON discount_products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users manage favourites" ON favourites; CREATE POLICY "Users manage favourites" ON favourites FOR ALL USING (auth.uid()=user_id);
DROP POLICY IF EXISTS "Wholesale view samples" ON sample_requests; CREATE POLICY "Wholesale view samples" ON sample_requests FOR SELECT USING (auth.uid()=user_id OR is_admin());
DROP POLICY IF EXISTS "Wholesale create samples" ON sample_requests; CREATE POLICY "Wholesale create samples" ON sample_requests FOR INSERT WITH CHECK (auth.uid()=user_id AND is_approved_wholesale());
DROP POLICY IF EXISTS "Admins manage samples" ON sample_requests; CREATE POLICY "Admins manage samples" ON sample_requests FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View orders" ON orders; CREATE POLICY "View orders" ON orders FOR SELECT USING (auth.uid()=user_id OR is_guest=true OR is_admin());
DROP POLICY IF EXISTS "Create orders" ON orders; CREATE POLICY "Create orders" ON orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admins manage orders" ON orders; CREATE POLICY "Admins manage orders" ON orders FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View order items" ON order_items; CREATE POLICY "View order items" ON order_items FOR SELECT USING (EXISTS(SELECT 1 FROM orders WHERE orders.id=order_items.order_id AND (orders.user_id=auth.uid() OR orders.is_guest=true)) OR is_admin());
