-- THE ESPRESSO LAB - FINAL WORKING DATABASE
-- COPY THIS ENTIRE FILE AND RUN IN SUPABASE SQL EDITOR

CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$ BEGIN CREATE TYPE user_role AS ENUM ('customer','wholesale','admin'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE approval_status AS ENUM ('pending','approved','rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE order_status AS ENUM ('pending_payment','payment_received','processing','qc_scheduled','qc_completed','shipped','delivered','cancelled','refunded'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE payment_method AS ENUM ('stripe','bank_transfer'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE booking_status AS ENUM ('pending','confirmed','cancelled','completed','rescheduled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE qc_appointment_status AS ENUM ('requested','scheduled','in_progress','completed','cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE notification_type AS ENUM ('order_placed','order_approved','order_shipped','qc_scheduled','qc_completed','course_booked','wholesale_approved','wholesale_rejected','sample_approved','sample_rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE discount_type AS ENUM ('percentage','fixed_amount','free_shipping'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE sample_request_status AS ENUM ('pending','approved','rejected','shipped','delivered'); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS companies (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), company_name TEXT NOT NULL, business_license TEXT, tax_id TEXT, address_line1 TEXT, city TEXT, country TEXT, phone TEXT, email TEXT, approval_status approval_status DEFAULT 'pending', approved_by UUID, approved_at TIMESTAMPTZ, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS profiles (id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, email TEXT UNIQUE NOT NULL, full_name TEXT, phone TEXT, role user_role DEFAULT 'customer' NOT NULL, approval_status approval_status DEFAULT 'pending', company_id UUID REFERENCES companies(id), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS categories (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sanity_id TEXT UNIQUE NOT NULL, slug TEXT UNIQUE NOT NULL, title_en TEXT NOT NULL, title_ar TEXT NOT NULL, description_en TEXT, description_ar TEXT, is_active BOOLEAN DEFAULT true, sort_order INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS collections (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sanity_id TEXT UNIQUE NOT NULL, slug TEXT UNIQUE NOT NULL, title_en TEXT NOT NULL, title_ar TEXT NOT NULL, description_en TEXT, description_ar TEXT, is_active BOOLEAN DEFAULT true, sort_order INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS taste_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sanity_id TEXT UNIQUE NOT NULL, title_en TEXT NOT NULL, title_ar TEXT NOT NULL, is_active BOOLEAN DEFAULT true, sort_order INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS roast_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sanity_id TEXT UNIQUE NOT NULL, title_en TEXT NOT NULL, title_ar TEXT NOT NULL, is_active BOOLEAN DEFAULT true, sort_order INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sanity_id TEXT UNIQUE NOT NULL, sku TEXT UNIQUE NOT NULL, category_id UUID REFERENCES categories(id), title_en TEXT NOT NULL, title_ar TEXT NOT NULL, description_en TEXT, description_ar TEXT, short_description_en TEXT, short_description_ar TEXT, price DECIMAL(10,2) NOT NULL, stock_quantity INTEGER DEFAULT 0 NOT NULL, low_stock_threshold INTEGER DEFAULT 10, is_active BOOLEAN DEFAULT true, is_wholesale_only BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), CONSTRAINT positive_stock CHECK (stock_quantity >= 0), CONSTRAINT positive_price CHECK (price >= 0));
CREATE TABLE IF NOT EXISTS product_collections (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, collection_id UUID REFERENCES collections(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(product_id, collection_id));
CREATE TABLE IF NOT EXISTS product_taste_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, taste_profile_id UUID REFERENCES taste_profiles(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(product_id, taste_profile_id));
CREATE TABLE IF NOT EXISTS product_roast_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, roast_profile_id UUID REFERENCES roast_profiles(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(product_id, roast_profile_id));
CREATE TABLE IF NOT EXISTS product_graph_1 (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, graph_name_en TEXT DEFAULT 'Acidity vs Body', graph_name_ar TEXT DEFAULT 'الحموضة مقابل القوام', value_x DECIMAL(5,2) NOT NULL, value_y DECIMAL(5,2) NOT NULL, label_x_en TEXT DEFAULT 'Acidity', label_x_ar TEXT DEFAULT 'الحموضة', label_y_en TEXT DEFAULT 'Body', label_y_ar TEXT DEFAULT 'القوام', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(product_id));
CREATE TABLE IF NOT EXISTS product_graph_2 (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, graph_name_en TEXT DEFAULT 'Sweetness vs Bitterness', graph_name_ar TEXT DEFAULT 'الحلاوة مقابل المرارة', value_x DECIMAL(5,2) NOT NULL, value_y DECIMAL(5,2) NOT NULL, label_x_en TEXT DEFAULT 'Sweetness', label_x_ar TEXT DEFAULT 'الحلاوة', label_y_en TEXT DEFAULT 'Bitterness', label_y_ar TEXT DEFAULT 'المرارة', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(product_id));
CREATE TABLE IF NOT EXISTS product_graph_3 (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, graph_name_en TEXT DEFAULT 'Aroma vs Aftertaste', graph_name_ar TEXT DEFAULT 'الرائحة مقابل الطعم المتبقي', value_x DECIMAL(5,2) NOT NULL, value_y DECIMAL(5,2) NOT NULL, label_x_en TEXT DEFAULT 'Aroma', label_x_ar TEXT DEFAULT 'الرائحة', label_y_en TEXT DEFAULT 'Aftertaste', label_y_ar TEXT DEFAULT 'الطعم المتبقي', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(product_id));
CREATE TABLE IF NOT EXISTS product_variants (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, sanity_id TEXT, sku TEXT UNIQUE NOT NULL, title_en TEXT, title_ar TEXT, price_adjustment DECIMAL(10,2) DEFAULT 0, stock_quantity INTEGER DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS carts (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, session_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS cart_items (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), cart_id UUID REFERENCES carts(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id) ON DELETE CASCADE, variant_id UUID REFERENCES product_variants(id), quantity INTEGER NOT NULL CHECK (quantity > 0), price_at_add DECIMAL(10,2) NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(cart_id, product_id, variant_id));
CREATE TABLE IF NOT EXISTS discounts (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), code TEXT UNIQUE NOT NULL, title_en TEXT NOT NULL, title_ar TEXT NOT NULL, description_en TEXT, description_ar TEXT, discount_type discount_type NOT NULL, discount_value DECIMAL(10,2) NOT NULL, min_purchase_amount DECIMAL(10,2) DEFAULT 0, max_discount_amount DECIMAL(10,2), usage_limit INTEGER, usage_count INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, valid_from TIMESTAMPTZ DEFAULT NOW(), valid_until TIMESTAMPTZ, is_wholesale_only BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS discount_products (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), discount_id UUID REFERENCES discounts(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(discount_id, product_id));
CREATE TABLE IF NOT EXISTS favourites (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id) ON DELETE CASCADE, variant_id UUID REFERENCES product_variants(id), created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(user_id, product_id, variant_id));
CREATE TABLE IF NOT EXISTS orders (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), order_number TEXT UNIQUE NOT NULL, user_id UUID REFERENCES profiles(id), company_id UUID REFERENCES companies(id), is_guest BOOLEAN DEFAULT false, guest_email TEXT, status order_status DEFAULT 'pending_payment', payment_method payment_method NOT NULL, payment_status TEXT DEFAULT 'pending', stripe_payment_intent_id TEXT, bank_transfer_receipt_url TEXT, discount_id UUID REFERENCES discounts(id), discount_code TEXT, discount_amount DECIMAL(10,2) DEFAULT 0, subtotal DECIMAL(10,2) NOT NULL, tax DECIMAL(10,2) DEFAULT 0, shipping_fee DECIMAL(10,2) DEFAULT 0, total_amount DECIMAL(10,2) NOT NULL, shipping_full_name TEXT NOT NULL, shipping_phone TEXT NOT NULL, shipping_address_line1 TEXT NOT NULL, shipping_city TEXT NOT NULL, shipping_country TEXT NOT NULL, tracking_number TEXT, shipped_at TIMESTAMPTZ, delivered_at TIMESTAMPTZ, notes TEXT, admin_notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS order_items (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), order_id UUID REFERENCES orders(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id), variant_id UUID REFERENCES product_variants(id), product_name TEXT NOT NULL, product_sku TEXT NOT NULL, variant_details JSONB, quantity INTEGER NOT NULL CHECK (quantity > 0), unit_price DECIMAL(10,2) NOT NULL, total_price DECIMAL(10,2) NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sample_requests (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), request_number TEXT UNIQUE NOT NULL, user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, company_id UUID REFERENCES companies(id), product_id UUID REFERENCES products(id), variant_id UUID REFERENCES product_variants(id), quantity INTEGER NOT NULL CHECK (quantity > 0), status sample_request_status DEFAULT 'pending', purpose TEXT, notes TEXT, admin_notes TEXT, approved_by UUID REFERENCES profiles(id), approved_at TIMESTAMPTZ, shipped_at TIMESTAMPTZ, tracking_number TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS inventory_transactions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), product_id UUID REFERENCES products(id) ON DELETE CASCADE, variant_id UUID REFERENCES product_variants(id), quantity_change INTEGER NOT NULL, transaction_type TEXT NOT NULL, reference_id UUID, notes TEXT, created_by UUID REFERENCES profiles(id), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS courses (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sanity_id TEXT UNIQUE NOT NULL, title_en TEXT NOT NULL, title_ar TEXT NOT NULL, description_en TEXT, description_ar TEXT, short_description_en TEXT, short_description_ar TEXT, price DECIMAL(10,2) NOT NULL, duration_minutes INTEGER, max_participants INTEGER DEFAULT 10, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS course_schedules (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), course_id UUID REFERENCES courses(id) ON DELETE CASCADE, start_time TIMESTAMPTZ NOT NULL, end_time TIMESTAMPTZ NOT NULL, available_slots INTEGER NOT NULL, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS course_bookings (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), course_id UUID REFERENCES courses(id) ON DELETE CASCADE, schedule_id UUID REFERENCES course_schedules(id) ON DELETE CASCADE, user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, participants_count INTEGER DEFAULT 1, status booking_status DEFAULT 'pending', payment_status TEXT DEFAULT 'pending', total_amount DECIMAL(10,2) NOT NULL, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qc_appointments (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), order_id UUID REFERENCES orders(id) ON DELETE CASCADE, user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, status qc_appointment_status DEFAULT 'requested', scheduled_date TIMESTAMPTZ, completed_date TIMESTAMPTZ, customer_notes TEXT, admin_notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qc_reports (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), appointment_id UUID REFERENCES qc_appointments(id) ON DELETE CASCADE, order_id UUID REFERENCES orders(id) ON DELETE CASCADE, inspector_id UUID REFERENCES profiles(id), overall_rating INTEGER CHECK (overall_rating >= 1 AND overall_rating <= 5), overall_notes TEXT, images_urls TEXT[], passed BOOLEAN, completed_at TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qc_answers (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), report_id UUID REFERENCES qc_reports(id) ON DELETE CASCADE, question_sanity_id TEXT NOT NULL, question_text TEXT NOT NULL, answer_value TEXT, rating INTEGER, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS qc_feedback (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), report_id UUID REFERENCES qc_reports(id) ON DELETE CASCADE, user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, rating INTEGER, comments TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notifications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES profiles(id) ON DELETE CASCADE, type notification_type NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, reference_id UUID, is_read BOOLEAN DEFAULT false, email_sent BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW());

CREATE INDEX IF NOT EXISTS idx_companies_approval ON companies(approval_status);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role); CREATE INDEX IF NOT EXISTS idx_profiles_company ON profiles(company_id);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku); CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_carts_user ON carts(user_id); CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON cart_items(cart_id);
CREATE INDEX IF NOT EXISTS idx_discounts_code ON discounts(code); CREATE INDEX IF NOT EXISTS idx_favourites_user ON favourites(user_id);
CREATE INDEX IF NOT EXISTS idx_sample_requests_user ON sample_requests(user_id); CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id); CREATE INDEX IF NOT EXISTS idx_orders_company ON orders(company_id); CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number);

CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at=NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION generate_order_number() RETURNS TEXT AS $$ DECLARE n TEXT; c INTEGER; BEGIN SELECT COUNT(*)+1 INTO c FROM orders; n:='TEL-'||TO_CHAR(NOW(),'YYYYMMDD')||'-'||LPAD(c::TEXT,4,'0'); RETURN n; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION generate_sample_request_number() RETURNS TEXT AS $$ DECLARE n TEXT; c INTEGER; BEGIN SELECT COUNT(*)+1 INTO c FROM sample_requests; n:='SMP-'||TO_CHAR(NOW(),'YYYYMMDD')||'-'||LPAD(c::TEXT,4,'0'); RETURN n; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION set_order_number() RETURNS TRIGGER AS $$ BEGIN IF NEW.order_number IS NULL THEN NEW.order_number:=generate_order_number(); END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION set_sample_request_number() RETURNS TRIGGER AS $$ BEGIN IF NEW.request_number IS NULL THEN NEW.request_number:=generate_sample_request_number(); END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION decrement_inventory_on_order() RETURNS TRIGGER AS $$ BEGIN IF NEW.status='payment_received' AND OLD.status='pending_payment' THEN UPDATE products p SET stock_quantity=stock_quantity-oi.quantity FROM order_items oi WHERE oi.order_id=NEW.id AND oi.product_id=p.id; UPDATE product_variants pv SET stock_quantity=stock_quantity-oi.quantity FROM order_items oi WHERE oi.order_id=NEW.id AND oi.variant_id=pv.id; INSERT INTO inventory_transactions(product_id,variant_id,quantity_change,transaction_type,reference_id) SELECT oi.product_id,oi.variant_id,-oi.quantity,'sale',NEW.id FROM order_items oi WHERE oi.order_id=NEW.id; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION increment_discount_usage() RETURNS TRIGGER AS $$ BEGIN IF NEW.discount_id IS NOT NULL THEN UPDATE discounts SET usage_count=usage_count+1 WHERE id=NEW.discount_id; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION is_admin() RETURNS BOOLEAN AS $$ SELECT EXISTS(SELECT 1 FROM profiles WHERE id=auth.uid() AND role='admin'); $$ LANGUAGE sql SECURITY DEFINER;
CREATE OR REPLACE FUNCTION is_approved_wholesale() RETURNS BOOLEAN AS $$ SELECT EXISTS(SELECT 1 FROM profiles WHERE id=auth.uid() AND role='wholesale' AND approval_status='approved'); $$ LANGUAGE sql SECURITY DEFINER;

DROP TRIGGER IF EXISTS update_companies_updated_at ON companies; CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles; CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_products_updated_at ON products; CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_carts_updated_at ON carts; CREATE TRIGGER update_carts_updated_at BEFORE UPDATE ON carts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_orders_updated_at ON orders; CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_sample_requests_updated_at ON sample_requests; CREATE TRIGGER update_sample_requests_updated_at BEFORE UPDATE ON sample_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS set_order_number_trigger ON orders; CREATE TRIGGER set_order_number_trigger BEFORE INSERT ON orders FOR EACH ROW EXECUTE FUNCTION set_order_number();
DROP TRIGGER IF EXISTS set_sample_request_number_trigger ON sample_requests; CREATE TRIGGER set_sample_request_number_trigger BEFORE INSERT ON sample_requests FOR EACH ROW EXECUTE FUNCTION set_sample_request_number();
DROP TRIGGER IF EXISTS decrement_inventory_trigger ON orders; CREATE TRIGGER decrement_inventory_trigger AFTER UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION decrement_inventory_on_order();
DROP TRIGGER IF EXISTS increment_discount_usage_trigger ON orders; CREATE TRIGGER increment_discount_usage_trigger AFTER INSERT ON orders FOR EACH ROW EXECUTE FUNCTION increment_discount_usage();

ALTER TABLE companies ENABLE ROW LEVEL SECURITY; ALTER TABLE profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE categories ENABLE ROW LEVEL SECURITY; ALTER TABLE collections ENABLE ROW LEVEL SECURITY; ALTER TABLE taste_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE roast_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE products ENABLE ROW LEVEL SECURITY; ALTER TABLE product_collections ENABLE ROW LEVEL SECURITY; ALTER TABLE product_taste_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE product_roast_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE product_graph_1 ENABLE ROW LEVEL SECURITY; ALTER TABLE product_graph_2 ENABLE ROW LEVEL SECURITY; ALTER TABLE product_graph_3 ENABLE ROW LEVEL SECURITY; ALTER TABLE carts ENABLE ROW LEVEL SECURITY; ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY; ALTER TABLE discounts ENABLE ROW LEVEL SECURITY; ALTER TABLE discount_products ENABLE ROW LEVEL SECURITY; ALTER TABLE favourites ENABLE ROW LEVEL SECURITY; ALTER TABLE sample_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE orders ENABLE ROW LEVEL SECURITY; ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "View companies" ON companies; CREATE POLICY "View companies" ON companies FOR SELECT USING (is_approved_wholesale() OR is_admin());
DROP POLICY IF EXISTS "Admins manage companies" ON companies; CREATE POLICY "Admins manage companies" ON companies FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "Users view profile" ON profiles; CREATE POLICY "Users view profile" ON profiles FOR SELECT USING (auth.uid()=id OR is_admin());
DROP POLICY IF EXISTS "Users update profile" ON profiles; CREATE POLICY "Users update profile" ON profiles FOR UPDATE USING (auth.uid()=id);
DROP POLICY IF EXISTS "Users insert profile" ON profiles; CREATE POLICY "Users insert profile" ON profiles FOR INSERT WITH CHECK (auth.uid()=id);
DROP POLICY IF EXISTS "View categories" ON categories; CREATE POLICY "View categories" ON categories FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage categories" ON categories; CREATE POLICY "Admins manage categories" ON categories FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View collections" ON collections; CREATE POLICY "View collections" ON collections FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage collections" ON collections; CREATE POLICY "Admins manage collections" ON collections FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View taste" ON taste_profiles; CREATE POLICY "View taste" ON taste_profiles FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage taste" ON taste_profiles; CREATE POLICY "Admins manage taste" ON taste_profiles FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View roast" ON roast_profiles; CREATE POLICY "View roast" ON roast_profiles FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage roast" ON roast_profiles; CREATE POLICY "Admins manage roast" ON roast_profiles FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View products" ON products; CREATE POLICY "View products" ON products FOR SELECT USING (is_active=true OR is_admin());
DROP POLICY IF EXISTS "Admins manage products" ON products; CREATE POLICY "Admins manage products" ON products FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View product collections" ON product_collections; CREATE POLICY "View product collections" ON product_collections FOR SELECT USING (true);
DROP POLICY IF EXISTS "View product taste" ON product_taste_profiles; CREATE POLICY "View product taste" ON product_taste_profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "View product roast" ON product_roast_profiles; CREATE POLICY "View product roast" ON product_roast_profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "View graph1" ON product_graph_1; CREATE POLICY "View graph1" ON product_graph_1 FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage graph1" ON product_graph_1; CREATE POLICY "Admins manage graph1" ON product_graph_1 FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View graph2" ON product_graph_2; CREATE POLICY "View graph2" ON product_graph_2 FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage graph2" ON product_graph_2; CREATE POLICY "Admins manage graph2" ON product_graph_2 FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View graph3" ON product_graph_3; CREATE POLICY "View graph3" ON product_graph_3 FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage graph3" ON product_graph_3; CREATE POLICY "Admins manage graph3" ON product_graph_3 FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "Users view cart" ON carts; CREATE POLICY "Users view cart" ON carts FOR SELECT USING (auth.uid()=user_id OR session_id IS NOT NULL);
DROP POLICY IF EXISTS "Users manage cart" ON carts; CREATE POLICY "Users manage cart" ON carts FOR ALL USING (auth.uid()=user_id OR session_id IS NOT NULL);
DROP POLICY IF EXISTS "Users view cart items" ON cart_items; CREATE POLICY "Users view cart items" ON cart_items FOR SELECT USING (EXISTS(SELECT 1 FROM carts WHERE carts.id=cart_items.cart_id AND (carts.user_id=auth.uid() OR carts.session_id IS NOT NULL)));
DROP POLICY IF EXISTS "Users manage cart items" ON cart_items; CREATE POLICY "Users manage cart items" ON cart_items FOR ALL USING (EXISTS(SELECT 1 FROM carts WHERE carts.id=cart_items.cart_id AND (carts.user_id=auth.uid() OR carts.session_id IS NOT NULL)));
DROP POLICY IF EXISTS "View discounts" ON discounts; CREATE POLICY "View discounts" ON discounts FOR SELECT USING (is_active=true);
DROP POLICY IF EXISTS "Admins manage discounts" ON discounts; CREATE POLICY "Admins manage discounts" ON discounts FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View discount products" ON discount_products; CREATE POLICY "View discount products" ON discount_products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users manage favourites" ON favourites; CREATE POLICY "Users manage favourites" ON favourites FOR ALL USING (auth.uid()=user_id);
DROP POLICY IF EXISTS "Wholesale view samples" ON sample_requests; CREATE POLICY "Wholesale view samples" ON sample_requests FOR SELECT USING (auth.uid()=user_id OR is_admin());
DROP POLICY IF EXISTS "Wholesale create samples" ON sample_requests; CREATE POLICY "Wholesale create samples" ON sample_requests FOR INSERT WITH CHECK (auth.uid()=user_id AND is_approved_wholesale());
DROP POLICY IF EXISTS "Admins manage samples" ON sample_requests; CREATE POLICY "Admins manage samples" ON sample_requests FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View orders" ON orders; CREATE POLICY "View orders" ON orders FOR SELECT USING (auth.uid()=user_id OR is_guest=true OR is_admin());
DROP POLICY IF EXISTS "Create orders" ON orders; CREATE POLICY "Create orders" ON orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admins manage orders" ON orders; CREATE POLICY "Admins manage orders" ON orders FOR ALL USING (is_admin());
DROP POLICY IF EXISTS "View order items" ON order_items; CREATE POLICY "View order items" ON order_items FOR SELECT USING (EXISTS(SELECT 1 FROM orders WHERE orders.id=order_items.order_id AND (orders.user_id=auth.uid() OR orders.is_guest=true)) OR is_admin());

ALTER PUBLICATION supabase_realtime ADD TABLE products; ALTER PUBLICATION supabase_realtime ADD TABLE carts; ALTER PUBLICATION supabase_realtime ADD TABLE orders; ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
